# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e47d0e55c77570a4a659932a41060bb1641fa2fcf778b55b8123da9142e2677ee72ba44ca66e8360f1f782a6852a5a7cb054b1e052ef7cca70dfcb933719d7
  
test:
  secret_key_base: 7cd6a440ff8882aebe14bbfe2d77795190f6f0f819a4ea6e6d0306e47562e3163e858332b462f74c06fc6ccd5c68609c75b04ef5210161043614d8b13b562b27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
